name: Exyron-FastCrystals
version: 1.0
api-version: 1.13
main: xyz.exyron.fastcrystals.FastCrystalsPlugin
authors: [ Exyron.XYZ, KamlaX, KinczeK ]
commands:
  fastcrystals:
    aliases: [ fastercrystals, fastcrystal ]